### ISSUE TITLE
doesn't build with `omd.1.0.0`

### ISSUE THREAD

**Issue by samoht** [ocaml/v2.ocaml.org#518]
Seems that you need `omd.0.9.7`, otherwise:

```
$ make opam.ocaml.org_template
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.opam.ocaml.org
cd script && \
    ocamlfind ocamlopt -annot -o ../"script/md_preprocess" -package omd,str,netstring -linkpkg \
      utils.cmx code_types.cmx code.ml md_preprocess.ml
File "md_preprocess.ml", line 20, characters 5-74:
Error: The constructor Html_block expects 3 argument(s),
       but is applied here to 1 argument(s)
```

**Comment by Chris00** [comment]
Went unnoticed because https://github.com/ocaml/opam/issues/1645

**Comment by Chris00** [comment]
See also https://github.com/mirage/ocaml-cow/issues/49

That said, I do not know how you could install the dependencies since `opam2web.1.3.1` requires `cow` which in turn requires `omd < 1.0.0`.

**Comment by samoht** [comment]
I'm using opam-lib and opam2web git versions. Need to make a stable for both of them when opam.1.2 is finally released.

**Comment by Chris00** [comment]
This is fixed in my repo but I will not push the fix — which would mandate using omd 1.0.0 for the site — until [this bug](https://github.com/ocaml/omd/issues/125) is resolved.

**Comment by pw374** [comment]
On 28 Aug 2014, at 22:16 pm, Christophe Troestler notifications@github.com wrote:

> This is fixed in my repo but I will not push the fix — which would mandate using omd 1.0.0 for the site — until this bug is resolved.

Yes, it’s a good thing to wait.

I’ve looked at the bug, it seems it’s not something trivial…
There is in index.md a block of 12 lines of HTML which multiplies the treatment time by more than 100, and I’m gonna be very busy until October, so there’s a good chance that it won’t be fixed before then.

**Comment by agarwal** [comment]
Would it be possible to move ahead with this fix now? So far I've kept a separate switch for ocaml.org, but that's difficult now.

**Comment by pw374** [comment]
The OMD-1.x.x-being-slow issue was solved so I think this can be closed.

Philippe Wang
(mail sent from a phone)

**Comment by agarwal** [comment]
@Chris00 Do you still have a patch to fix the original error of this issue. If not, I can work on it.

**Comment by Chris00** [comment]
On Fri, 24 Oct 2014 05:52:58 -0700, Ashish Agarwal wrote:

> @Chris00 Do you still have a patch to fix the original error of 
> this issue. If not, I can work on it.

Yes, I still have the branch.  I'll try to merge it over the WE but 
there was still a slowness problem with `md_prprocess` that I have 
had no time to track yet.

**Comment by pw374** [comment]
I've just tried building ocaml.org.

Well, it doesn't seem significantly slower with omd.1.1.1 than with omd.0.9.7. (I haven't formally measured, I just wanted to see if there was a major performance issue) 
However I've tried without `opam2web` (because it failed to compile with ocaml 4.02.1) and `site/learn/tutorials/camlp4_3.10/pa_foreach3.cmo` (because it failed to compile).

```
File "site/learn/tutorials/camlp4_3.10/pa_foreach3.ml", line 29, characters 15-31:
Error: This expression has type string but an expression was expected of type
         Camlp4.PreCast.Syntax.Ast.patt = Camlp4.PreCast.Ast.patt
```

Also, my "patch" of `md_preprocess` was the quickest one, basically something like `s/Html/Raw/g`, so there might be some slowdown if the omd.1.1.1's `Html` is used (I don't know because I haven't tried).

**Comment by Chris00** [comment]
On Fri, 24 Oct 2014 17:55:50 -0700, Philippe Wang wrote:

> Well, it doesn't seem significantly slower with omd.1.1.1 than with 
> omd.0.9.7.

I quickly tested with omd 1.1.1 (my previous test were with earlier 
versions of omd) and it indeed seems resonably fast.  I'll make more 
tests today and merge it if all goes fine.

**Comment by Chris00** [comment]
On Fri, 24 Oct 2014 05:52:58 -0700, Ashish Agarwal wrote:

> @Chris00 Do you still have a patch to fix the original error of thi 
> s issue. If not, I can work on it.

Now that it compiles the site at reasonable speed, I can see that the 
re are a few more things to fix.  I'll do that ASAP — not enough time 
 this weekend.

**Comment by Chris00** [comment]
Porting the scripts is WIP.  I am afraid we will need a version of omd [later](https://github.com/ocaml/omd/issues/136) [than](https://github.com/ocaml/omd/issues/137) 1.1.2.

**Comment by pw374** [comment]
[1.1.3 is on its way](https://github.com/ocaml/opam-repository/pull/2993).

**Comment by Chris00** [comment]
I pushed my work to a [new branch](https://github.com/ocaml/ocaml.org/tree/omd).  Once [these](https://github.com/ocaml/omd/issues/141) [problems](https://github.com/ocaml/omd/issues/142) in omd are fixed, I think it can be merged — and the server updated.

**Comment by pw374** [comment]
Let's hope 1.2.1 (not yet released but might be https://github.com/ocaml/omd/commit/93e91ac16094d709676a31ecfdd57beee8bc0947) will be the right version.

**Comment by Chris00** [comment]
Unfortunately, we really need https://github.com/ocaml/omd/issues/144 to be fixed. Fixing https://github.com/ocaml/omd/issues/143 would be nice too but I removed the `<!-- FIXME -->` in the Markdown document so it is less urgent.

**Comment by pw374** [comment]
https://github.com/ocaml/omd/issues/144 and https://github.com/ocaml/omd/issues/143 have been fixed, hopefully!

**Comment by pw374** [comment]
1.2.1 is on its way to opam: https://github.com/ocaml/opam-repository/pull/3004

**Comment by Chris00** [comment]
It seems OK with omd 1.2.1.  Thanks to @pw374 for tirelessly fixing my bug reports!

I'll leave this open in case some other people want to check the branch — and comment — and do the merge during the weekend.

**Comment by pw374** [comment]
And thank you @Chris00 for reporting all those nasty bugs! I have to admit that for a moment I wondered what would be quicker between rewriting omd from scratch and fixing those bugs...

**Comment by Chris00** [comment]
I have upgraded `opam` on the server (using the git repository) and all packages.  I merged the branch `omd`.

Remark: When installing `opam2web`, `opam` performed a **downgrade cow from 1.0.0 to 0.6.1**.   Also `opamfu`  depends on `opam.client` which is now `opam`.  I had to pin `opamfu` and `opam2web` to the dev versions (cloned and the `opam2web` opam file modified to depend on cow ≥ 1.0.0).

**Comment by samoht** [comment]
I've released opam-lib 1.2, need to release the correspondong opamfu and opam2web. I'll do it at one point but I'fine maybe @dsheets will do it before me if he has time (I doubt it, but well...) :p
